export default {
  foregroundColors: [
    'statusBar.foreground',
    'badge.foreground',
    'activityBarBadge.foreground',
    'button.foreground',
    'debugConsole.warningForeground',
    'extensionButton.prominentForeground',
  ],
  themeColors: [
    'activityBarBadge.background',
    'button.background',
    'button.hoverBackground',
    'extensionButton.prominentBackground',
    'extensionButton.prominentHoverBackground',
    'progressBar.background',
    'statusBar.background',
    'statusBar.noFolderBackground',
    'titleBar.activeForeground',
    'activityBar.activeBorder',
    'activityBar.foreground',
    'breadcrumb.focusForeground',
    'descriptionForeground',
    'editorCursor.foreground',
    'editorLineNumber.activeForeground',
    'editorSuggestWidget.highlightForeground',
    'list.activeSelectionForeground',
    'list.filterMatchBorder',
    'list.focusForeground',
    'list.highlightForeground',
    'listFilterWidget.outline',
    'panelTitle.activeBorder',
    'sash.hoverBorder',
    'tab.activeBorder',
    'tab.hoverForeground',
    'textLink.foreground',
    'textLink.activeForeground',
    'badge.background',
    'tab.activeForeground',
  ],
  borderColors: [
    'titleBar.border',
    'tab.unfocusedActiveBorder',
    'sideBar.border',
    'sideBarSectionHeader.border',
    'list.filterMatchBackground',
    'focusBorder',
    'editorGroup.border',
    'activityBar.border',
    'panel.border',
  ],
  highlightColors: [
    'textLink.activeForeground',
    'extensionButton.prominentHoverBackground',
    'button.hoverBackground',
  ],
}
